#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────────────────
#  PLATFORM: macOS ONLY.
#
#  This deployer relies on AppleScript + launchd + macOS's keychain — none
#  of which exist on Linux or Windows. If you ever need a Linux or Windows
#  equivalent it would need a different driver entirely (e.g. CDP-connect
#  to a separately-running Chrome on Linux, PowerShell + Windows UIA on
#  Windows) and live as `scripts/deploy-linux.sh` / `scripts/deploy-windows.ps1`.
#  Those do not currently exist.
# ────────────────────────────────────────────────────────────────────────
#
# One-and-done installer for the oversoles cookie-refresh job.
#
# Copies refresh.ts + login.applescript out of the repo into
#   ~/Library/Application Support/b2b-scrapers/
# installs its own node_modules there, copies your credentials, detects the
# GitHub repo for secret syncing, and registers a weekly LaunchAgent.
#
# After this runs, the source repo can be deleted — the refresh job lives
# independently in ~/Library/Application Support/b2b-scrapers/ and the
# LaunchAgent points at that location, not at the repo.
#
# Usage:     bash scripts/deploy-macos.sh
# Uninstall: launchctl unload ~/Library/LaunchAgents/com.b2b-scrapers.oversoles-refresh.plist
#            rm ~/Library/LaunchAgents/com.b2b-scrapers.oversoles-refresh.plist
#            rm -rf "$HOME/Library/Application Support/b2b-scrapers"

set -euo pipefail

# Optional --interval N flag: run every N seconds instead of weekly Monday 4am.
# Use for testing the pipeline end-to-end on a fast cadence (e.g. 300 = 5 min).
# Without the flag, the LaunchAgent uses the production weekly schedule.
INTERVAL_SECONDS=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --interval)
      INTERVAL_SECONDS="$2"; shift 2 ;;
    *)
      echo "[deploy-macos] unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ "$(uname)" != "Darwin" ]]; then
  echo "[deploy-macos] this script is macOS-only — uname reports $(uname)" >&2
  exit 1
fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_DIR="$HOME/Library/Application Support/b2b-scrapers"
LOG_DIR="$HOME/Library/Logs"
AGENT_NAME="com.b2b-scrapers.oversoles-refresh"
PLIST_DEST="$HOME/Library/LaunchAgents/${AGENT_NAME}.plist"

SRC_REFRESH="$REPO_ROOT/scripts/oversoles-refresh-cookies.ts"
SRC_APPLESCRIPT="$REPO_ROOT/scripts/oversoles-auto-login.applescript"
SRC_ENV="$REPO_ROOT/.env"

# --- Preflight ----------------------------------------------------------
for f in "$SRC_REFRESH" "$SRC_APPLESCRIPT"; do
  [[ -f "$f" ]] || { echo "[deploy-macos] missing $f" >&2; exit 1; }
done
if [[ ! -f "$SRC_ENV" ]]; then
  echo "[deploy-macos] $SRC_ENV does not exist — create it with OVERSOLES_LOGIN and OVERSOLES_PASSWORD first" >&2
  exit 1
fi
command -v npm >/dev/null 2>&1 || { echo "[deploy-macos] npm not on PATH" >&2; exit 1; }

mkdir -p "$TARGET_DIR" "$LOG_DIR" "$HOME/Library/LaunchAgents"

# --- Copy source files --------------------------------------------------
cp "$SRC_REFRESH" "$TARGET_DIR/oversoles-refresh-cookies.ts"
cp "$SRC_APPLESCRIPT" "$TARGET_DIR/oversoles-auto-login.applescript"

# --- Generate minimal package.json --------------------------------------
cat > "$TARGET_DIR/package.json" <<'EOF'
{
  "name": "b2b-scrapers-oversoles-refresh",
  "private": true,
  "type": "module",
  "description": "Deployed copy of the oversoles cookie refresher. Generated by scripts/deploy-macos.sh.",
  "dependencies": {
    "chrome-cookies-secure": "^3.0.2",
    "dotenv": "^16.6.1",
    "tsx": "^4.19.0"
  }
}
EOF

# --- Build target .env --------------------------------------------------
# Pull credentials and any pre-existing session blob from the repo .env.
get_env_val() {
  local key="$1"
  local f="$2"
  grep -E "^${key}=" "$f" 2>/dev/null | head -n1 | cut -d= -f2- || true
}
LOGIN_VAL="$(get_env_val OVERSOLES_LOGIN "$SRC_ENV")"
PASS_VAL="$(get_env_val OVERSOLES_PASSWORD "$SRC_ENV")"
SESSION_VAL="$(get_env_val OVERSOLES_SESSION_B64 "$SRC_ENV")"

if [[ -z "$LOGIN_VAL" || -z "$PASS_VAL" ]]; then
  echo "[deploy-macos] OVERSOLES_LOGIN / OVERSOLES_PASSWORD missing or empty in $SRC_ENV" >&2
  exit 1
fi

# Detect the GitHub repo (best-effort) so the deployed copy can sync the
# Actions secret independently of the source-repo working tree.
GH_REPO_VAL=""
if command -v gh >/dev/null 2>&1; then
  if (cd "$REPO_ROOT" && gh repo view >/dev/null 2>&1); then
    GH_REPO_VAL="$(cd "$REPO_ROOT" && gh repo view --json nameWithOwner -q .nameWithOwner)"
  fi
fi

cat > "$TARGET_DIR/.env" <<EOF
# Auto-generated by scripts/deploy-macos.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Edit credentials here if they change; the LaunchAgent will pick up edits
# automatically on its next run.
OVERSOLES_LOGIN=$LOGIN_VAL
OVERSOLES_PASSWORD=$PASS_VAL
OVERSOLES_SESSION_B64=$SESSION_VAL
GH_REPO=$GH_REPO_VAL
EOF
chmod 600 "$TARGET_DIR/.env"

# --- Install deps inside the deployed dir -------------------------------
echo "[deploy-macos] installing node_modules under $TARGET_DIR (this may take ~20s)..."
(cd "$TARGET_DIR" && npm install --silent --no-audit --no-fund)

# --- Write LaunchAgent plist --------------------------------------------
ESCAPED_TARGET="${TARGET_DIR//&/&amp;}"
ESCAPED_LOG="${LOG_DIR//&/&amp;}"
if [[ -n "$INTERVAL_SECONDS" ]]; then
  SCHEDULE_BLOCK="  <key>StartInterval</key>
  <integer>${INTERVAL_SECONDS}</integer>"
  SCHEDULE_DESC="every ${INTERVAL_SECONDS}s"
else
  SCHEDULE_BLOCK="  <key>StartCalendarInterval</key>
  <dict>
    <key>Weekday</key><integer>1</integer>
    <key>Hour</key><integer>4</integer>
    <key>Minute</key><integer>0</integer>
  </dict>"
  SCHEDULE_DESC="Mondays 04:00 local"
fi
cat > "$PLIST_DEST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTD/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${AGENT_NAME}</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>-lc</string>
    <string>cd "${ESCAPED_TARGET}" &amp;&amp; ./node_modules/.bin/tsx oversoles-refresh-cookies.ts</string>
  </array>
  <key>WorkingDirectory</key>
  <string>${ESCAPED_TARGET}</string>
${SCHEDULE_BLOCK}
  <key>RunAtLoad</key>
  <false/>
  <key>StandardOutPath</key>
  <string>${ESCAPED_LOG}/oversoles-refresh.log</string>
  <key>StandardErrorPath</key>
  <string>${ESCAPED_LOG}/oversoles-refresh.log</string>
</dict>
</plist>
EOF

launchctl unload "$PLIST_DEST" 2>/dev/null || true
launchctl load "$PLIST_DEST"

cat <<EOF

================================================================
  Deployed to:     $TARGET_DIR
  LaunchAgent:     $PLIST_DEST  (${SCHEDULE_DESC})
  Logs:            $LOG_DIR/oversoles-refresh.log
  GitHub sync:     ${GH_REPO_VAL:-disabled (no gh repo detected; set GH_REPO in $TARGET_DIR/.env to enable)}

  ONE-TIME SETUP — required before the first run will succeed:

   1. Open Google Chrome.
   2. Menu bar: View → Developer → Allow JavaScript from Apple Events.
      (If 'Developer' isn't there, enable it in Chrome Settings → Show
      Develop menu — or chrome://flags, search 'JavaScript from Apple
      Events'.)
   3. Confirm you're logged into oversoles.com in that Chrome profile.

  Then validate the deploy with a manual run:
      cd "$TARGET_DIR" && ./node_modules/.bin/tsx oversoles-refresh-cookies.ts

  On first run macOS will prompt for keychain access ('Chrome Safe
  Storage') — click 'Always Allow' so future scheduled runs don't prompt.

  Trigger the schedule immediately (instead of waiting for Monday):
      launchctl start $AGENT_NAME

  After this point you can rm -rf the repo if you want — this deployed
  copy is fully self-contained.
================================================================
EOF
